// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhzhtqcncdxoyclobrkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpoemh0cWNuY2R4b3ljbG9icmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTE1MDIsImV4cCI6MjA1Njk4NzUwMn0.LbWkeQkMWyU2P-VFUmls70XwNW9lAQskQEQdcTj5XM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);